[workspace]
members = ["fnmock", "fnmock-derive", "fnmock-tests"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["Jakob Rzeppa <rzeppa.jakob@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/jakob-rzeppa/fnmock"
description = "A Rust mocking framework for standalone functions and methods in an impl block."
keywords = ["mock", "mocking", "testing", "test", "fake"]
categories = ["development-tools::testing"]
readme = "README.md"
