[package]
name = "fnmock-derive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macro implementation for the fnmock mocking framework."
keywords.workspace = true
categories.workspace = true
readme.workspace = true
documentation = "https://docs.rs/fnmock-derive"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "visit", "visit-mut"] }
quote = "1.0"
proc-macro2 = "1.0"