//! Proof of concept of the spy API described in `docs/EXPECTATIONS.md`.
//!
//! [`get_user`] and [`save_user`] are written the way `#[fnmock::spy]` will eventually expand a
//! spied function, by hand. They exist to drive the parts of the `fnmock` crate a spy is built
//! from (`matcher`, `expectation`, `sequence`, `spy_store`) through the API a test will see,
//! before any of it is generated by a macro.

mod get_user;
mod save_user;

#[cfg(test)]
mod cross_function;
#[cfg(test)]
mod expectations;
