[package]
name = "fnmock-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "fnmock-tests"
path = "src/main.rs"
doc = false

[dependencies]
"fnmock" = { path = "../fnmock" }
"tokio" = { version = "1.49.0", features = ["full"]}

[dev-dependencies]
"trybuild" = "1"

[lints.clippy]
all = "allow"