use std::fmt::Debug;

/// Low-level struct for mocking a function's behavior and tracking calls.
///
/// `FunctionMock` is automatically generated by the `#[mock_function]` attribute macro.
/// **Users should not interact with this struct directly** - instead, use the generated proxy module
/// that provides a clean API.
///
/// # Generics
///
/// - `Params: Clone + PartialEq + Debug + 'static` - The function parameters as a tuple
/// - `Result` - The function's return type
///
/// # How it works with the macro
///
/// When you apply `#[mock_function]` to a function, the macro generates:
/// 1. **The mocked function** - wrapper that delegates to the mock infrastructure
/// 2. **A proxy module** - named `<function_name>_mock` containing convenience functions
/// 3. **An instance of FunctionMock** - stored in thread-local storage for thread safety
///
/// The proxy module wraps this struct and provides a convenient API:
/// - `setup(fn)` - Configure the mock with a custom implementation
/// - `clear()` - Reset the mock state
/// - `is_set()` - Check if a mock implementation is configured
/// - `call(params)` - Execute the mock (called automatically by the mocked function)
/// - `assert_times(n)` - Assert the function was called exactly n times
/// - `assert_with(params)` - Assert the function was called with specific parameters
///
/// # Macro Expansion
///
/// When you apply `#[mock_function]` to this function:
/// ```ignore
/// #[mock_function]
/// pub fn send_email(user: String, body: String) -> Result<(), String> {
///     println!("Sending email to {}: {}", user, body);
///     Ok(())
/// }
/// ```
///
/// The macro generates two things:
///
/// **1. The wrapped function:**
/// ```ignore
/// pub fn send_email(user: String, body: String) -> Result<(), String> {
///     #[cfg(test)]
///     if send_email_mock::is_set() {
///         return send_email_mock::call((user, body));
///     }
///
///     println!("Sending email to {}: {}", user, body);
///     Ok(())
/// }
/// ```
///
/// **2. The proxy module:**
/// ```ignore
/// pub(crate) mod send_email_mock {
///     use super::*;
///
///     thread_local! {
///         static MOCK: std::cell::RefCell<fnmock::function_mock::FunctionMock<
///             (String, String),
///             Result<(), String>,
///         >> = std::cell::RefCell::new(
///             fnmock::function_mock::FunctionMock::new("send_email_mock")
///         );
///     }
///
///     pub(crate) fn call(params: (String, String)) -> Result<(), String> {
///         MOCK.with(|mock| { mock.borrow_mut().call(params) })
///     }
///
///     pub(crate) fn setup(new_f: fn((String, String)) -> Result<(), String>) {
///         MOCK.with(|mock| { mock.borrow_mut().setup(new_f) })
///     }
///
///     pub(crate) fn clear() {
///         MOCK.with(|mock| { mock.borrow_mut().clear() })
///     }
///
///     pub(crate) fn is_set() -> bool {
///         MOCK.with(|mock| { mock.borrow().is_set() })
///     }
///
///     pub(crate) fn assert_times(expected_num_of_calls: u32) {
///         MOCK.with(|mock| { mock.borrow().assert_times(expected_num_of_calls) })
///     }
///
///     pub(crate) fn assert_with(user: String, body: String) {
///         MOCK.with(|mock| { mock.borrow().assert_with((user, body)) })
///     }
/// }
/// ```
///
/// # Internal Fields
///
/// - `name` - Function name for error messages
/// - `implementation` - Optional custom implementation function
/// - `calls` - Record of all parameters passed to the mock
pub struct FunctionMock<Params, Result> where Params: Clone + PartialEq + Debug + 'static {
    name: String,
    implementation: Option<fn(Params) -> Result>,
    calls: Vec<Params>,
}

impl<Params, Result> FunctionMock<Params, Result> where Params: Clone + PartialEq + Debug + 'static {
    pub fn new(function_name: &str) -> Self {
        Self {
            name: function_name.to_string(),
            implementation: None,
            calls: Vec::new(),
        }
    }

    // --- Mocking ---

    pub fn setup(&mut self, new_f: fn(Params) -> Result) {
        self.implementation = Some(new_f);
    }

    pub fn clear(&mut self) {
        self.implementation = None;
        self.calls = Vec::new();
    }

    pub fn is_set(&self) -> bool {
        self.implementation.is_some()
    }

    // --- Execute ---

    pub fn call(&mut self, params: Params) -> Result {
        let implementation = self.implementation
            .as_ref()
            .expect(format!("{} mock not initialized", self.name).as_str());

        self.calls.push(params.clone());
        implementation(params)
    }

    // --- Assert ---

    pub fn assert_times(&self, expected_num_of_calls: u32) {
        assert_eq!(
            self.calls.len(),
            expected_num_of_calls as usize,
            "Expected {} mock to be called {} times, received {}",
            self.name,
            self.calls.len(),
            expected_num_of_calls
        );
    }

    pub fn assert_with(&self, params: Params) {
        let mut was_called_with = false;

        for called_params in self.calls.iter() {
            if *called_params == params {
                was_called_with = true;
            }
        }

        assert!(was_called_with, "Expected {} mock to be called with {:?}", self.name, params);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Helper mock function for testing
    fn add_mock_implementation(params: (i32, i32)) -> i32 {
        params.0 + params.1
    }

    fn multiply_mock_implementation(params: (i32, i32)) -> i32 {
        params.0 * params.1
    }

    fn string_concat_mock_implementation(params: (String, String)) -> String {
        format!("{}{}", params.0, params.1)
    }

    #[test]
    fn test_new_creates_mock_with_correct_name() {
        let mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("test_function");
        assert_eq!(mock.name, "test_function");
        assert!(mock.implementation.is_none());
        assert!(mock.calls.is_empty());
    }

    #[test]
    fn test_mock_implementation_sets_function() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);
        assert!(mock.implementation.is_some());
    }

    #[test]
    fn test_call_executes_mocked_function() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);

        let result = mock.call((5, 3));
        assert_eq!(result, 8);
    }

    #[test]
    #[should_panic(expected = "add mock not initialized")]
    fn test_call_panics_when_not_initialized() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.call((5, 3));
    }

    #[test]
    fn test_call_records_parameters() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);

        mock.call((5, 3));
        mock.call((10, 20));

        assert_eq!(mock.calls.len(), 2);
        assert_eq!(mock.calls[0], (5, 3));
        assert_eq!(mock.calls[1], (10, 20));
    }

    #[test]
    fn test_clear_mock_resets_state() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);
        mock.call((5, 3));
        mock.call((10, 20));

        assert_eq!(mock.calls[0], (5, 3));
        assert_eq!(mock.calls[1], (10, 20));

        mock.clear();

        assert!(mock.implementation.is_none());
        assert!(mock.calls.is_empty());
    }

    #[test]
    fn test_mock_can_be_replaced() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("math");
        mock.setup(add_mock_implementation);

        let result1 = mock.call((5, 3));
        assert_eq!(result1, 8);

        mock.setup(multiply_mock_implementation);
        let result2 = mock.call((5, 3));
        assert_eq!(result2, 15);
    }

    #[test]
    fn test_assert_times_passes_with_correct_count() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);

        mock.call((1, 2));
        mock.call((3, 4));
        mock.call((5, 6));

        mock.assert_times(3);
    }

    #[test]
    #[should_panic(expected = "Expected add mock to be called 2 times, received 5")]
    fn test_assert_times_fails_with_wrong_count() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);

        mock.call((1, 2));
        mock.call((3, 4));

        mock.assert_times(5);
    }

    #[test]
    fn test_assert_times_with_zero_calls() {
        let mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.assert_times(0);
    }

    #[test]
    fn test_assert_with_passes_when_called_with_params() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);

        mock.call((5, 3));
        mock.call((10, 20));

        mock.assert_with((5, 3));
        mock.assert_with((10, 20));
    }

    #[test]
    #[should_panic(expected = "Expected add mock to be called with (7, 8)")]
    fn test_assert_with_fails_when_not_called_with_params() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);

        mock.call((5, 3));
        mock.assert_with((7, 8));
    }

    #[test]
    fn test_assert_with_finds_params_among_multiple_calls() {
        let mut mock: FunctionMock<(i32, i32), i32> = FunctionMock::new("add");
        mock.setup(add_mock_implementation);

        mock.call((1, 1));
        mock.call((2, 2));
        mock.call((3, 3));
        mock.call((4, 4));

        mock.assert_with((3, 3));
    }

    #[test]
    fn test_with_string_parameters() {
        let mut mock: FunctionMock<(String, String), String> = FunctionMock::new("concat");
        mock.setup(string_concat_mock_implementation);

        let result = mock.call(("Hello".to_string(), "World".to_string()));
        assert_eq!(result, "HelloWorld");

        mock.assert_times(1);
        mock.assert_with(("Hello".to_string(), "World".to_string()));
    }

    #[test]
    fn test_with_single_parameter() {
        fn double_mock(params: i32) -> i32 {
            params * 2
        }

        let mut mock: FunctionMock<i32, i32> = FunctionMock::new("double");
        mock.setup(double_mock);

        let result = mock.call(5);
        assert_eq!(result, 10);

        mock.assert_times(1);
        mock.assert_with(5);
    }

    #[test]
    fn test_with_unit_return_type() {
        fn void_mock(_params: i32) -> () {
            // Do nothing
        }

        let mut mock: FunctionMock<i32, ()> = FunctionMock::new("void_fn");
        mock.setup(void_mock);

        mock.call(42);
        mock.assert_times(1);
        mock.assert_with(42);
    }

    #[test]
    fn test_with_result_return_type() {
        fn result_mock(params: (i32, i32)) -> Result<i32, String> {
            if params.1 == 0 {
                Err("Division by zero".to_string())
            } else {
                Ok(params.0 / params.1)
            }
        }

        let mut mock: FunctionMock<(i32, i32), Result<i32, String>> = FunctionMock::new("divide");
        mock.setup(result_mock);

        let result1 = mock.call((10, 2));
        assert_eq!(result1, Ok(5));

        let result2 = mock.call((10, 0));
        assert_eq!(result2, Err("Division by zero".to_string()));

        mock.assert_times(2);
    }

    #[test]
    fn test_multiple_calls_preserve_order() {
        let mut mock: FunctionMock<i32, i32> = FunctionMock::new("identity");
        mock.setup(|x| x);

        mock.call(1);
        mock.call(2);
        mock.call(3);

        assert_eq!(mock.calls, vec![1, 2, 3]);
    }
}
