/// Low-level struct for faking a function with a custom implementation.
///
/// `FunctionFake` is automatically generated by the `#[fake_function]` attribute macro.
/// **Users should not interact with this struct directly** - instead, use the generated proxy module
/// that provides a clean API.
///
/// Unlike mocks, fakes do not track call history - they only provide custom behavior substitution.
///
/// # Generics
///
/// - `Function: 'static + Copy` - The function implementation type (typically a function pointer like `fn(Args) -> Return`)
///
/// # How it works with the macro
///
/// When you apply `#[fake_function]` to a function, the macro generates:
/// 1. **The faked function** - wrapper that delegates to the fake infrastructure
/// 2. **A proxy module** - named `<function_name>_fake` containing convenience functions
/// 3. **An instance of FunctionFake** - stored in thread-local storage for thread safety
///
/// The proxy module wraps this struct and provides a convenient API:
/// - `setup(fn)` - Configure the fake with a custom implementation
/// - `clear()` - Reset the fake to use the original implementation
/// - `is_set()` - Check if a custom implementation is configured
/// - `get_implementation()` - Retrieve the current implementation (called by the faked function)
///
/// # Macro Expansion
///
/// When you apply `#[fake_function]` to this function:
/// ```ignore
/// #[fake_function]
/// pub fn calculate(x: i32, y: i32) -> i32 {
///     x + y
/// }
/// ```
///
/// The macro generates two things:
///
/// **1. The wrapped function:**
/// ```ignore
/// pub fn calculate(x: i32, y: i32) -> i32 {
///     #[cfg(test)]
///     if calculate_fake::is_set() {
///         return calculate_fake::get_implementation()(x, y);
///     }
///
///     x + y
/// }
/// ```
///
/// **2. The proxy module:**
/// ```ignore
/// pub(crate) mod calculate_fake {
///     use super::*;
///
///     thread_local! {
///         static FAKE: std::cell::RefCell<fnmock::function_fake::FunctionFake<
///             fn(i32, i32) -> i32
///         >> = std::cell::RefCell::new(
///             fnmock::function_fake::FunctionFake::new("calculate_fake")
///         );
///     }
///
///     pub(crate) fn setup(new_f: fn(i32, i32) -> i32) {
///         FAKE.with(|fake| { fake.borrow_mut().setup(new_f) })
///     }
///
///     pub(crate) fn clear() {
///         FAKE.with(|fake| { fake.borrow_mut().clear() })
///     }
///
///     pub(crate) fn is_set() -> bool {
///         FAKE.with(|fake| { fake.borrow().is_set() })
///     }
///
///     pub(crate) fn get_implementation() -> fn(i32, i32) -> i32 {
///         FAKE.with(|fake| { fake.borrow().get_implementation() })
///     }
/// }
/// ```
///
/// # Internal Fields
///
/// - `name` - Function name for error messages
/// - `implementation` - Optional custom implementation function
pub struct FunctionFake<Function> where Function: 'static + Copy {
    name: String,
    implementation: Option<Function>,
}

impl<Function> FunctionFake<Function> where Function: 'static + Copy {
    pub fn new(function_name: &str) -> Self {
        Self {
            name: function_name.to_string(),
            implementation: None,
        }
    }

    // --- Faking ---

    pub fn setup(&mut self, new_f: Function) {
        self.implementation = Some(new_f);
    }

    pub fn clear(&mut self) {
        self.implementation = None;
    }

    pub fn is_set(&self) -> bool {
        self.implementation.is_some()
    }

    pub fn get_implementation(&self) -> Function {
        self.implementation.expect(format!("{} fake not initialized", self.name).as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Helper fake functions for testing
    fn add_fake_implementation(a: i32, b: i32) -> i32 {
        a + b
    }

    fn multiply_fake_implementation(a: i32, b: i32) -> i32 {
        a * b
    }

    fn string_concat_fake_implementation(a: String, b: String) -> String {
        format!("{}{}", a, b)
    }

    fn sum_fake_implementation(name: &[u32]) -> u32 {
        name.iter().sum()
    }

    #[test]
    fn test_new_creates_fake_with_correct_name() {
        let fake: FunctionFake<fn(i32, i32) -> i32> = FunctionFake::new("test_function");
        assert_eq!(fake.name, "test_function");
        assert!(fake.implementation.is_none());
    }

    #[test]
    fn test_fake_implementation_sets_function() {
        let mut fake: FunctionFake<fn(i32, i32) -> i32> = FunctionFake::new("add");
        fake.setup(add_fake_implementation);
        assert!(fake.implementation.is_some());
    }

    #[test]
    fn test_get_implementation_returns_function() {
        let mut fake: FunctionFake<fn(i32, i32) -> i32> = FunctionFake::new("add");
        fake.setup(add_fake_implementation);

        let implementation = fake.get_implementation();
        let result = implementation(5, 3);
        assert_eq!(result, 8);
    }

    #[test]
    #[should_panic(expected = "add fake not initialized")]
    fn test_get_implementation_panics_when_not_initialized() {
        let fake: FunctionFake<fn(i32, i32) -> i32> = FunctionFake::new("add");
        fake.get_implementation();
    }

    #[test]
    fn test_clear_fake_resets_implementation() {
        let mut fake: FunctionFake<fn(i32, i32) -> i32> = FunctionFake::new("add");
        fake.setup(add_fake_implementation);

        assert!(fake.implementation.is_some());

        fake.clear();

        assert!(fake.implementation.is_none());
    }

    #[test]
    fn test_fake_can_be_replaced() {
        let mut fake: FunctionFake<fn(i32, i32) -> i32> = FunctionFake::new("math");
        fake.setup(add_fake_implementation);

        let implementation1 = fake.get_implementation();
        let result1 = implementation1(5, 3);
        assert_eq!(result1, 8);

        fake.setup(multiply_fake_implementation);
        let implementation2 = fake.get_implementation();
        let result2 = implementation2(5, 3);
        assert_eq!(result2, 15);
    }

    #[test]
    fn test_with_string_parameters() {
        let mut fake: FunctionFake<fn(String, String) -> String> = FunctionFake::new("concat");
        fake.setup(string_concat_fake_implementation);

        let implementation = fake.get_implementation();
        let result = implementation("Hello".to_string(), "World".to_string());
        assert_eq!(result, "HelloWorld");
    }

    #[test]
    fn test_with_reference_parameter() {
        let mut fake: FunctionFake<fn(&[u32]) -> u32> = FunctionFake::new("sum");
        fake.setup(sum_fake_implementation);

        let vec = vec![1, 2, 3];

        let implementation = fake.get_implementation();
        let result = implementation(vec.as_slice());
        assert_eq!(result, 6);
    }

    #[test]
    fn test_with_unit_return_type() {
        fn void_fake(_x: i32) -> () {
            // Do nothing
        }

        let mut fake: FunctionFake<fn(i32) -> ()> = FunctionFake::new("void_fn");
        fake.setup(void_fake);

        let implementation = fake.get_implementation();
        implementation(42); // Should not panic
    }

    #[test]
    fn test_with_result_return_type() {
        fn divide_fake(a: i32, b: i32) -> Result<i32, String> {
            if b == 0 { Err("Division by zero".to_string()) } else { Ok(a / b) }
        }

        let mut fake: FunctionFake<fn(i32, i32) -> Result<i32, String>> = FunctionFake::new(
            "divide"
        );
        fake.setup(divide_fake);

        let implementation = fake.get_implementation();

        let result1 = implementation(10, 2);
        assert_eq!(result1, Ok(5));

        let result2 = implementation(10, 0);
        assert_eq!(result2, Err("Division by zero".to_string()));
    }

    #[test]
    fn test_with_option_return_type() {
        fn safe_divide_fake(a: i32, b: i32) -> Option<i32> {
            if b == 0 { None } else { Some(a / b) }
        }

        let mut fake: FunctionFake<fn(i32, i32) -> Option<i32>> = FunctionFake::new("safe_divide");
        fake.setup(safe_divide_fake);

        let implementation = fake.get_implementation();

        let result1 = implementation(10, 2);
        assert_eq!(result1, Some(5));

        let result2 = implementation(10, 0);
        assert_eq!(result2, None);
    }

    #[test]
    fn test_multiple_get_implementation_calls() {
        let mut fake: FunctionFake<fn(i32, i32) -> i32> = FunctionFake::new("add");
        fake.setup(add_fake_implementation);

        let impl1 = fake.get_implementation();
        let impl2 = fake.get_implementation();

        assert_eq!(impl1(5, 3), 8);
        assert_eq!(impl2(10, 20), 30);
    }

    #[test]
    fn test_function_name_preserved() {
        let fake: FunctionFake<fn(i32) -> i32> = FunctionFake::new("my_custom_function");
        assert_eq!(fake.name, "my_custom_function");
    }
}
